import { Type, type Schema } from '@google/genai';

const str: Schema = { type: Type.STRING };
const strArr: Schema = { type: Type.ARRAY, items: { type: Type.STRING } };
const score: Schema = { type: Type.INTEGER, minimum: 1, maximum: 10 };

/**
 * Esquema de salida estructurada para Gemini. Garantiza JSON válido con la
 * forma exacta de `CardAnalysis` — sin necesidad de parsear texto libre.
 */
export const cardAnalysisSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    titulo: str,
    resumenCorto: str,
    resumenDetallado: str,
    ideaPrincipal: str,
    aprendizajes: strArr,
    consejos: strArr,
    acciones: strArr,
    checklist: strArr,
    herramientas: strArr,
    apps: strArr,
    webs: strArr,
    libros: strArr,
    personas: strArr,
    empresas: strArr,
    prompts: strArr,
    frameworks: strArr,
    metodos: strArr,
    conceptos: strArr,
    erroresComunes: strArr,
    analisisCritico: str,
    fuentesDetectadas: strArr,
    textoEnPantalla: strArr,
    categoria: str,
    etiquetas: strArr,
    nivel: { type: Type.STRING, enum: ['básico', 'intermedio', 'avanzado'] },
    idioma: str,
    tiempoLecturaMin: { type: Type.INTEGER, minimum: 1 },
    evaluacion: {
      type: Type.OBJECT,
      properties: {
        utilidad: score,
        accionable: score,
        originalidad: score,
        claridad: score,
        fiabilidad: { type: Type.STRING, enum: ['alta', 'media', 'baja'] },
        mereceGuardarse: { type: Type.BOOLEAN },
        tiempoAhorradoMin: { type: Type.INTEGER, minimum: 0 },
        necesitaVerificacion: { type: Type.BOOLEAN },
        afirmacionesDudosas: strArr,
      },
      required: [
        'utilidad',
        'accionable',
        'originalidad',
        'claridad',
        'fiabilidad',
        'mereceGuardarse',
        'tiempoAhorradoMin',
        'necesitaVerificacion',
        'afirmacionesDudosas',
      ],
    },
  },
  required: [
    'titulo',
    'resumenCorto',
    'resumenDetallado',
    'ideaPrincipal',
    'aprendizajes',
    'consejos',
    'acciones',
    'checklist',
    'herramientas',
    'apps',
    'webs',
    'libros',
    'personas',
    'empresas',
    'prompts',
    'frameworks',
    'metodos',
    'conceptos',
    'erroresComunes',
    'analisisCritico',
    'fuentesDetectadas',
    'textoEnPantalla',
    'categoria',
    'etiquetas',
    'nivel',
    'idioma',
    'tiempoLecturaMin',
    'evaluacion',
  ],
};
